### ISSUE TITLE
Question about usage

### ISSUE THREAD

**Issue by jordiyapz** [Saravananslb/py-googletranslation#17]
How to use the proxy feature in Translator(proxy)? With some examples maybe...

**Comment by Saravananslb** [comment]
Hi Jordiyapz,

Thanks for writing,
>>> from pygoogletranslation import Translator
>>> translator = Translator(proxies=YOUR_PROXIES)

Thanks,
Saravanan

**Comment by jordiyapz** [comment]
I mean with actual proxy. What is supposed to be passed as YOUR_PROXIES?
