### ISSUE TITLE
How to use the proxy features?

### ISSUE THREAD

**Issue by jordiyapz** [Saravananslb/py-googletranslation#19]
Could you provide us some example on using the Translator(proxies=YOUR_PROXY) with actual proxy? 

I've tried passing it with string and FreeProxy object from [free-proxy](https://pypi.org/project/free-proxy/) module but none worked.

**Comment by finia2NA** [comment]
The package seems to just pass what was given as the "proxies" argument [straight to the requests library](https://github.com/Saravananslb/py-googletranslation/blob/a8d37778a0a11ba56d5515912326b15499c64a90/pygoogletranslation/translate.py#L184):

The documentation of this says that the proxies parameter expects a:
> Dictionary mapping protocol to the URL of the proxy.

An example is given [here](https://requests.readthedocs.io/en/master/user/advanced/#proxies). Seems simple enough :)

**Comment by Saravananslb** [comment]
Hi Users,

    >>> from pygoogletranslation import Translator
    >>> proxy = {"http":"http://sampleproxy.com:80"}
    >>> translator = Translator(proxies=proxy)

Sorry for the inconvenience caused. please refer doc for further .

Thanks,
Saravanan N
