### ISSUE TITLE
Is there an offline version of this library？whether the corresponding text can be translated when the network is disconnected 

### ISSUE THREAD

**Issue by mashagua** [Saravananslb/py-googletranslation#24]

**Comment by johann-lau** [comment]
This library, as its name says, is based on Google Translate. Human-language translation is not just replacing text. It is also analysing grammar. An offline translator is of course *possible* (that's what Google do in their end), but the file size will not be optimal and I don't think it will be Pythonic.

**Comment by mashagua** [comment]
> This library, as its name says, is based on Google Translate. Human-language translation is not just replacing text. It is also analysing grammar. An offline translator is of course _possible_ (that's what Google do in their end), but the file size will not be optimal and I don't think it will be Pythonic.

Thany you for your reply
