### ISSUE TITLE
Exception: Unexpected status code 429 from https://translate.googleapis.com/translate_a/

### ISSUE THREAD

**Issue by Lier007** [Saravananslb/py-googletranslation#6]
After multiple requests, this error is reported

Traceback (most recent call last):
  File "D:/code/google_trans_new/tmp", line 45, in <module>
    status = (translator.translate(text, dest="zh-cn").text)
  File "C:\Users\Admin\Anaconda3\envs\tf\lib\site-packages\pygoogletranslation\translate.py", line 55, in translate
    data = self._translate(text, src=src, dest=dest)
  File "C:\Users\Admin\Anaconda3\envs\tf\lib\site-packages\pygoogletranslation\translate.py", line 169, in _translate
    raise Exception('Unexpected status code {} from {}'.format(response.status_code, self.host))
Exception: Unexpected status code 429 from https://translate.googleapis.com/translate_a/

**Comment by Saravananslb** [comment]
Hi Lier007,

We have updated our package to bring a solution for your issue.
Please try new version 2.0.2, visit below for more information,
https://pypi.org/project/pygoogletranslation/2.0.2/

We are closing this issue, if you still facing the same please send a text which you are trying to translate to us. we are ready to work for your issue.

Thanks,
Saravananslb

**Comment by jonas-nothnagel** [comment]
The initial error was removed, but now it gives:

`AttributeError: 'list' object has no attribute 'replace'`

I was using the example code:
`
from pygoogletranslation import Translator
translator = Translator()
translations = translator.translate(['this is google translation', 'Tamil language' ], dest='ta')
for translation in translations:
    print(translation.origin, ' -> ', translation.text)
`
