### ISSUE TITLE
ValueError: invalid destination language

### ISSUE THREAD

**Issue by mashagua** [Saravananslb/py-googletranslation#7]
when i run print(translator.translate('good morning',dest="zh-CN")),give an error:
ValueError: invalid destination language I want to know how to replace dest if I want to translate english to chinese?

**Comment by mashagua** [comment]
I already know,it's 'zh-cn'

**Comment by Saravananslb** [comment]
We have updated our package to new version 2.0.3 which accept language as case insensitive.

**Comment by mashagua** [comment]
> 
> 
> We have updated our package to new version 2.0.3 which accept language as case insensitive.

thank you for your reply.
